shift = 5
text ='hello world'

def caesar():
    alphabet = 'abcdefghijklmnopqrstuvwxyz'
    shifted_alphabet = (alphabet[shift:])+alphabet[:shift]
#print(shifted_alphabet)
    translation_table = str.maketrans(alphabet, shifted_alphabet)
#print(translation_table)
   
    encrypted_text = text.translate(translation_table)
    print(translation_table)
    print(encrypted_text)

#PASSAGGIO_12
text = 'freeCodeCamp'
shift = 3
def caesar(text,shift):
    alphabet = 'abcdefghijklmnopqrstuvwxyz'
    shifted_alphabet = (alphabet[shift:])+alphabet[:shift]
#print(shifted_alphabet)
    translation_table = str.maketrans(alphabet, shifted_alphabet)
#print(translation_table)
   
    encrypted_text = text.translate(translation_table)
    print(translation_table)
    return(encrypted_text)
    
encrypted_text = caesar(text,shift)
print(encrypted_text)

#PASSAGGIO_14
#rendere la funzione riutilizzabile sempre
def caesar(text, shift):
    alphabet = 'abcdefghijklmnopqrstuvwxyz'
    shifted_alphabet = alphabet[shift:] + alphabet[:shift]
    translation_table = str.maketrans(alphabet, shifted_alphabet)
    #encrypted_text = text.translate(translation_table)
    return(text.translate(translation_table))

encrypted_text = caesar('freeCodeCamp', 3)
print(encrypted_text)

#PASSAGGIO_15
#rendere disponibile anche i caratteri maiuscoli nel cifrario
#costruire due variabili che sono gli alfabeti maiuscoli e minuscoli 
#insieme
def caesar(text, shift):
    alphabet = 'abcdefghijklmnopqrstuvwxyz'
    upper_alphabet = alphabet.upper()
    total_alphabet = alphabet + upper_alphabet
    shifted_alphabet = alphabet[shift:] + alphabet[:shift]
    shifted_alphabet_upper = (shifted_alphabet.upper())
    upper_shifted_alphabet = shifted_alphabet + shifted_alphabet_upper
    
    
    
    translation_table = str.maketrans(total_alphabet, upper_shifted_alphabet)
    return text.translate(translation_table)
    
encrypted_text = caesar('FREECODECAMP', 3)
print(encrypted_text)

#MAKETRANS
#The str.maketrans() method takes two strings of equal 
#length and returns a translation table that maps each character 
#of the first string with the corresponding character of the second 
#string. Each character in the translation table is stored as 
#a Unicode ordinal, a number that uniquely identifies the character.

lower_chars = 'abc'
upper_chars = 'ABC'

table = str.maketrans(lower_chars, upper_chars)
print(table) # {97: 65, 98: 66, 99: 67}

#TRANSLATE
#The translate() method takes as argument the translation table 
#generated by str.maketrans(). It is called on a string and returns 
#a copy of the original string where the characters have been replaced 
#based on the translation table:

t = ('lk','br')
t_t = str.maketrans('lk', 'br')
sentence = 'The tent gave in to the leaks.'
print (sentence)
print('translate:',t)
print(t_t)
print(sentence.translate(t_t))
# Output: The tent gave in to the bears.
